# External Ansible roles required by this repository

- src: openmicroscopy.basedeps
  version: 1.0.1

- src: openmicroscopy.ice
  version: 2.1.1

- src: openmicroscopy.omego
  version: 0.1.1

- src: openmicroscopy.omero-common
  version: 0.3.0

- src: openmicroscopy.omero-python-deps
  version: 1.1.0

- src: openmicroscopy.omero-web
  version: 2.0.1
